name: Build Python Dependencies Layer

on:
  workflow_dispatch:
  push:
    paths:
      - "requirements.txt"   # only rebuild when dependencies change

jobs:
  build-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # Compress the venv for reuse
          tar -czf python-layer.tar.gz venv

      - name: Upload dependency layer
        uses: actions/upload-artifact@v4
        with:
          name: python-layer
          path: python-layer.tar.gz
