name: EMA+ADX Multi-Coin Scanner

on:
  schedule:
<<<<<<< HEAD
    - cron: "*/15 * * * *"  # Runs every 15 minutes (UTC)
  workflow_dispatch:        # Allows manual trigger from GitHub UI
=======
    - cron: "*/12 * * * *"  # ⏰ Runs every 12 minutes (UTC)
  workflow_dispatch:          # 🚀 Allows manual trigger from GitHub UI
>>>>>>> 6d5983b (✨ Add startup system test (Telegram + CSV) and set 12-minute GitHub Actions schedule)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # 3️⃣ Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies (fast, system-wide)
      - name: Install dependencies (UV)
        run: |
          pip install uv
          uv pip install --system -r requirements.txt

      # 5️⃣ Run startup test (only once per job)
      - name: Run startup system test
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "🧪 Running startup system test (Telegram + CSV)..."
          python startup.py

      # 6️⃣ Run the main EMA+ADX strategy
      - name: Run EMA+ADX Bot
        env:
<<<<<<< HEAD
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
=======
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
>>>>>>> 6d5983b (✨ Add startup system test (Telegram + CSV) and set 12-minute GitHub Actions schedule)
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "🚀 Running EMA+ADX Multi-Coin Scanner..."
          python main.py

<<<<<<< HEAD
      # 6️⃣ Optional: Commit logs or output results if needed
=======
      # 7️⃣ Commit updated signals/logs
>>>>>>> 6d5983b (✨ Add startup system test (Telegram + CSV) and set 12-minute GitHub Actions schedule)
      - name: Commit results
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add signals_journal.csv logs/ || true
<<<<<<< HEAD
          git commit -m "Update signals or logs from scheduled run" || true
=======
          git commit -m "📈 Auto-update: Signals or logs from 12-min scan" || true
>>>>>>> 6d5983b (✨ Add startup system test (Telegram + CSV) and set 12-minute GitHub Actions schedule)
          git push origin main || true
