name: EMA+ADX Signal Bot

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:

jobs:
  run-strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pandas requests ta python-telegram-bot

      - name: Run main strategy
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          COINS: ${{ secrets.COINS }}
          LTF_INTERVAL: "15m"
          HTF_INTERVAL: "1h"
          JOURNAL_FILE: "signals_journal.csv"
        run: python main.py

      - name: Commit and push all changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add -A
          git diff --cached --quiet || git commit -m "🪶 Auto-update from EMA+ADX bot"
          git push
